import L from "leaflet";
import "leaflet/dist/leaflet.css";

export default {
  clickedIcon: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#c50101;' class='marker-pin-selected'></div><i class='material-icons' style='font-size: 18px; color: #5f0101'>circle</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  farmIcon: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#FFAB00;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color: grey'>solar_power</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  officeIcon: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#01579B;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color: grey'>fax</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  machineryIcon: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#C0CA33;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color: grey'>factory</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  processingIcon: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#c30b82;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color: grey'>factory</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  marketIcon: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#AA00FF;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color: grey'>shopping_basket</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  nurseryIcon: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#64DD17;' class='marker-pin'></div><span class='mdi mdi-sprout' style='font-size: 18px; color: grey'></span>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  schoolIcon: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#90A4AE;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color: grey'>school</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  weatherIcon: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#FFEB3B;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color:grey'>thermostat</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  waterIcon: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#1E88E5;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color: grey'>water_drop</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  digitalIcon: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#6CC8DA;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color: grey'>rss_feed</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  defaultIcon: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#c50101;' class='marker-pin-selected'></div><i class='material-icons' style='font-size: 18px; color: #5f0101'>circle</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  //class2icons
  Milling_Machines: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#01579B;' class='marker-pin'></div><span class='mdi mdi-mortar-pestle' style='font-size: 18px; color: grey'></span>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  Boreholes: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#B71C1C;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color: grey'>adjust</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  biogasDigester: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#AFB42B;' class='marker-pin'></div><span class='mdi mdi-gas-burner' style='font-size: 18px; color: grey'></span>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  coffeeCupping: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#E57373;' class='marker-pin'></div><span class='mdi mdi-coffee-maker' style='font-size: 18px; color: grey'></span>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  coffeePulping: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#827717;' class='marker-pin'></div><span class='mdi mdi-factory' style='font-size: 18px; color: grey'></span>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  Communication: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#01579B;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color: grey'>wifi</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  cooperativeOffice: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#3F51B5;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color: grey'>groups</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  demonstrationPlot: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#01579B;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color: grey'>tour</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  farmerFieldSchools: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#64DD17;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color: grey'>local_library</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  FertilizerTrial: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#FF9800;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color: grey'>science</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  incubator: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#01579B;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color: grey'>icon_name</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  irrigation: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#29B6F6;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color: grey'>water</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  learningHub: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#E91E63;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color: grey'>hub</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  marketCentre: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#E91E63;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color: grey'>payments</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  moistureMeters: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#40C4FF;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color: grey'>water</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  Nursery: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#01579B;' class='marker-pin'></div><span class='mdi mdi-sprout' style='font-size: 18px; color: grey'></span>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  onionStorage: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#607D8B;' class='marker-pin'></div><span class='mdi mdi-silo' style='font-size: 18px; color: grey'></span>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  pilateMachines: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#E91E63;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color: grey'>precision_manufacturing</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  PoultryFeedsGrinder: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#01579B;' class='marker-pin'></div><span class='mdi mdi-mortar-pestle' style='font-size: 18px; color: grey'></span>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  Processing: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#1B5E20;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color: grey'>icon_name</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  projectOffice: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#E91E63;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color: grey'>gite</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  QualityAssurance: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#8BCC00;' class='marker-pin'></div><span class='mdi mdi-package' style='font-size: 18px; color: grey'></span>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  centralPulpingUnit: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#827717;' class='marker-pin'></div><span class='mdi mdi-factory' style='font-size: 18px; color: grey'></span>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  screenHouse: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#21BA45;' class='marker-pin'></div><span class='mdi mdi-greenhouse' style='font-size: 18px; color: grey'></span>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  SoilScanners: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#01579B;' class='marker-pin'></div><span class='mdi mdi-landslide' style='font-size: 18px; color: grey'></span>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  SolarDryers: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#FFB300;' class='marker-pin'></div><span class='mdi mdi-solar-power-variant' style='font-size: 18px; color: grey'></span>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  SolarPoweredPump: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#FFC107;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color: grey'>solar_power</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  TeaFactory: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#6D4C41;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color: grey'>factory</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  TeaLeafAnalysisScanner: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#1B5E20;' class='marker-pin'></div><span class='mdi mdi-leaf' style='font-size: 18px; color: grey'></span>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  TeaMotherBush: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#AFB42B;' class='marker-pin'></div><span class='mdi mdi-tree' style='font-size: 18px; color: grey'></span>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
  WeatherStation: L.divIcon({
    className: "custom-div-icon",
    html: "<div style='background-color:#E91E63;' class='marker-pin'></div><i class='material-icons' style='font-size: 18px; color: grey'>thermostat</i>",
    iconSize: [30, 42],
    iconAnchor: [15, 42],
  }),
};
